### ISSUE TITLE
Collect Log from Specific APPs only

### ISSUE THREAD

**Issue by moficodes** [logdna/logdna-agent-v2#158]
I have logdna agent installed on a k8s cluster.

I only want to collect logs for a few specific apps.

1. Do I need to write the log in any specific way? Right now the logs are written to stdout. (I can see the log in /var/log/pods, or /var/data/kubeletlogs) 
2. I do not want to collect logs for any other pods. like kubelet or coredns.  I tried adding this exclusion rule. Then adding inclusion rule for just my app, not sure if i did that right.
```yaml
            - name: LOGDNA_EXCLUSION_RULES
              value: /var/log/**/*
            - name: LOGDNA_LOG_DIRS
              value: /var/log/pods/kubeadmin*/*
```

Any guidance/help is appreciated.
