### ISSUE TITLE
Helm Chart: log enrichment and k8s events not captured by default

### ISSUE THREAD

**Issue by karrth** [logdna/logdna-agent-v2#235]
After deploying cart version `203.2.4`, the agent did not enrich logs or pull k8s events until I specified the following environment variables.  The README indicated this should happen by default.
```
values:
    extraEnv:
      - name: LOGDNA_LOG_K8S_EVENTS
        value: 'always'
      - name: LOGDNA_USE_K8S_LOG_ENRICHMENT
        value: 'always'
```
