### ISSUE TITLE
Is there any way to disable journald listenning ? why it always show the message in /var/log/message, even exclude it?

### ISSUE THREAD

**Issue by jpixy** [logdna/logdna-agent-v2#358]
Hi Team,
Here is the background.
Here is my logdna-agent v2 config yaml:
```
  exclude:
    glob:
          - /var/log/at/*
          - /var/log/anaconda/*
          - /var/log/audit/*
          - /var/log/boot*
          - /var/log/btmp*
          - /var/log/chrony/*
          - /var/log/cloud-init*
          - /var/log/cron*
          - /var/log/dnf*
          - /var/log/falcon*
          - /var/log/firewalld*
          - /var/log/hawkey*
          - /var/log/insights-client*
          - /var/log/journal/*
          - /var/log/kdump
          - /var/log/lastlog
          - /var/log/maillog
          - /var/log/messages*
          - /var/log/openvpn.log
          - /var/log/private/*
          - /var/log/qemu*/*
          - /var/log/rhsm/*
          - /var/log/secure*
          - /var/log/spooler*
          - /var/log/sssd/*
          - /var/log/sudo.log
          - /var/log/tuned/*
          - /var/log/wtmp
          - /var/log/btmp
          - /var/log/utmp
          - /var/log/wtmpx
          - /var/log/btmpx
          - /var/log/utmpx
          - /var/log/asl/**
          - /var/log/sa/**
          - /var/log/sar*
          - /var/log/tallylog
          - /var/log/fluentd-buffers/**/*
          - /var/log/pods/**/*
          - /run/systemd/journal/*
    regex: []
  use_k8s_enrichment: ~
  log_k8s_events: ~
journald:
  paths:
    - /root/Download
```
I blocked most files in /var/log. and try to block all journal log in /var/log/journal/* and  /run/systemd/journal/*
But I still got these log from agent:

![image](https://user-images.githubusercontent.com/13565121/173836549-2416f329-3132-4eca-b50e-58200f9689fd.png)

I searched the log content, I found some of them are in /var/log/message file. even I have exclude it.

I think maybe the root cause is the journald , Listening to journalctl , then will send log like in screenshot.

So if it was the root cause, how can I disable "Listening to journalctl" ?
If it is not  the root cause, How can I block the "init.scopr" or "user@0.service" .... log  ?

Thanks
