### ISSUE TITLE
Line exclusion rules don't seem to take effect

### ISSUE THREAD

**Issue by tishma** [logdna/logdna-agent-v2#359]
Hi, it's either missing in the docs, but as far as I am concerned, `LOGDNA_LINE_EXCLUSION_REGEX` doesn't seem to be working.
My idea was to suppress agent's own log messages, by adding:
`LOGDNA_LINE_EXCLUSION_REGEX=(?:logdna\-agent)`.
Also tried:
`LOGDNA_LINE_EXCLUSION_REGEX=(?:logdna-agent)`
I was able to achieve the similar effect by editing exclusion rules in the GUI, but why not save some traffic on the agent side.

**Comment by stephen-hill** [comment]
I too have a similar issue:

```yaml
log:
  dirs:
    - "/var/log"
  exclude:
    glob:
      - "*init.scope"
      - "*veeaminstaller.log"
      - "*veeamconfig.log"
      - "*veeamsvc.log.log"
    regex: []
  line_exclusion_regex:
    - "veeammaservice"
journald:
  line_exclusion_regex:
    - "veeammaservice"
```

But app:veeammaservice.service lines still appear in Mezmo. And also init.scope also appears. It would be very helpful if the developers provided a kitchen sink example config.yaml.
