### ISSUE TITLE
How to do ignore rules in kubernetes?

### ISSUE THREAD

**Issue by vorandrew** [logdna/logdna-agent-v2#497]
My cluster sending too much logs, Can I ignore\include patterns?

**Comment by jakedipity** [comment]
You can use the `LOGDNA_EXCLUSION_RULES` or `LOGDNA_INCLUSION_RULES` environment variables with a glob like pattern to include/exclude files and directories from monitoring. There's also a regex equivalent for these. More information can be found [here](https://github.com/logdna/logdna-agent-v2#options)

**Comment by vorandrew** [comment]
But how do I do it through HELM chart?

**Comment by vorandrew** [comment]
You are not overriding. 

```
extraEnv:
  - name: LOGDNA_INCLUSION_RULES
    value: /var/log/pods/dev-**
```

Still gives me ` - "*.log"`

Because of `INFO config: read the following options from cli, env and config:`


```
log:
  dirs:
    - /var/log/
  include:
    glob:
      - "*.log"
      - /var/log/pods/dev-**

```

**Comment by vorandrew** [comment]
News?

**Comment by dkhokhlov** [comment]
@vorandrew 

this log & journald options should work:

```
log:
  dirs:
    - /var/log/containers
  include:
    glob:
      - "*/dev*.log"
    regex: []
  exclude:
    glob: []
    regex: []
journald:
  systemd_journal_tailer: false
```
Notes:
- log_dir is set to /var/log/containers
- journal log is disabled (source of system logs too)
