### ISSUE TITLE
Exclusion not working

### ISSUE THREAD

**Issue by stdmje** [logdna/logdna-agent-v2#571]
I am trying to include all logs from a specific namespace but excluding the pods with a label and is not working.

```
extraEnv:
  - name: LOGDNA_K8S_METADATA_LINE_INCLUSION
    value: namespace:vcluster-ihq-demos
  - name: LOGDNA_K8S_METADATA_LINE_EXCLUSION
    value: "label.vcluster.loft.sh/namespace:kube-system"
````

I can see all the logs from the pods of that namespace including the ones with that label.

Am i missing something?

Thanks for the help
